# This is a basic workflow to help you get started with Actions

name: CI - My Web App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Provision Azure services required by the app
  provision:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Repo Check-out
        uses: actions/checkout@v3

      - name: Azure Authentication
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      
      - name: Deploy Azure App Services
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\src\ps\app-service-deploy.ps1

  # This workflow contains a single job called "build"
  build:

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
